easy_admin:
  design:
    menu:
      - {label: "Entities"}
      - label: "Poll"
        children:
          - {entity: Poll, label: "List", icon: "th-list" }
          - {entity: Poll, label: "Manage", icon: "pencil", params: {action: "myList"}}
      - label: "Responder"
        children:
          - {entity: Responder, label: "List", icon: "th-list" }
          - {entity: Responder, label: "Add", icon: "plus", params: {action: "new"}}
      - label: "Survey"
        children:
          - {entity: Survey, label: "List", icon: "th-list" }
          - {entity: Survey, label: "Add", icon: "plus", params: {action: "new"}}
      - label: "Questions"
        children:
          - {entity: Question, label: "List", icon: "th-list" }
          - {entity: Question, label: "Add", icon: "question", params: {action: "new"}}
      - label: "Option"
        children:
          - {entity: Option, label: "List", icon: "th-list" }
          - {entity: Option, label: "Add", icon: "dog", params: {action: "new"}}
      - label: "Answer"
        children:
          - {entity: Answer, label: "List", icon: "th-list" }
      - {label: "Super Admin", permission: 'ROLE_SUPER_ADMIN'}
      - label: "Actions"
        permission: 'ROLE_SUPER_ADMIN'
        children:
          - {label: "SlackBot Settings", icon: "cog", route: "bot_settings", permission: 'ROLE_SUPER_ADMIN' }
          - {label: "Import Responders", icon: "file-import", route: "responder_import", permission: 'ROLE_SUPER_ADMIN'}
          - {entity: User, icon: "user", permission: 'ROLE_SUPER_ADMIN'}
  site_name: "NFQ Pulse"
  user:
    name_property_path: "email"
    display_name: true
  entities:
    # List the entity class name you want to manage
    Responder:
      class: App\Entity\Responder
      label: "Responder"
      form:
        fields:
          - { property: 'slackId',
              help:
                '<a href="https://help.workast.com/hc/en-us/articles/360027461274-How-to-find-a-Slack-user-ID"
                target="_blank">How to find a Slack user ID</a>' }
          - email
          - slackUsername
          - department
          - jobTitle
          - teamLead
          - fullName
          - site
          - team
          - answers
      list:
        fields:
          - slackId
          - email
          - slackUsername
          - department
    Question:
      class: App\Entity\Question
      label: "Question"
      form:
        fields:
          - { property: 'questionNumber', help: 'Question number in a poll row' }
          - question
          - poll
          - options
          - poll
      list:
        fields:
          - questionNumber
          - question
          - poll
          - options
    Survey:
      class: App\Entity\Survey
      label: "Survey"
      controller: App\Controller\SurveyController
      form:
        fields:
          - name
          - datetime
          - poll
      list:
        fields:
          - id
          - name
          - datetime
          - poll
          - answers
        actions:
          - 'graph'
          - show
    Poll:
      class: App\Entity\Poll
      label: "Poll"
      controller: App\Controller\PollController
      form:
        fields:
          - name
          - user
          - questions
          - surveys
      list:
        collapse_actions: true
        fields:
          - id
          - name
          - user
          - questions
          - surveys
        actions:
          - { name: 'send_team', type: 'route' }
          - { name: 'send_workspace', type: 'route' }
          - 'formEdit'
    User:
      class: App\Entity\User
      label: "User"
      form:
        fields:
          - email
          - password
          - polls
          - responders
      list:
        fields:
          - id
          - email
          - roles
          - password
          - polls
          - responders
    Answer:
      class: App\Entity\Answer
      label: "Answer"
      form:
        fields:
          - value
          - answerOption
          - responder
          - survey
      list:
        actions: ['-edit', '-new']
        fields:
          - value
          - survey
    Option:
      class: App\Entity\Option
      label: "Option"
      form:
        fields:
          - value
          - question
          - answers
      list:
        fields:
          - id
          - value
          - question
          - answers