easy_admin:
  design:
    menu:
      - {label: "Entities"}
      - label: "Questions"
        children:
          - {entity: Question, label: "List", icon: "th-list" }
          - {entity: Question, label: "Add", icon: "plus", params: {action: "new"}}
      - label: "Responder"
        children:
          - {entity: Responder, label: "List", icon: "th-list" }
          - {entity: Responder, label: "Add", icon: "plus", params: {action: "new"}}
      - label: "Survey"
        children:
          - {entity: Survey, label: "List", icon: "th-list" }
          - {entity: Survey, label: "Add", icon: "plus", params: {action: "new"}}
      - label: "Poll"
        children:
          - {entity: Poll, label: "List", icon: "th-list" }
          - {entity: Poll, label: "Add", icon: "plus", params: {action: "new"}}
          - {entity: Poll, label: "Results", icon: "plus", params: {action: "show"}}
      - label: "Option"
        children:
          - {entity: Option, label: "List", icon: "th-list" }
          - {entity: Option, label: "Add", icon: "plus", params: {action: "new"}}
      - label: "Answer"
        children:
          - {entity: Answer, label: "List", icon: "th-list" }
          - {entity: Answer, label: "Add", icon: "plus", params: {action: "new"}}
      - {label: "Settings"}
      - {entity: User, icon: "user", permission: 'ROLE_SUPER_ADMIN'}
  site_name: "NFQ Pulse"
  user:
    name_property_path: "email"
    display_name: true
  entities:


    # List the entity class name you want to manage
    Responder:
      class: App\Entity\Responder
      label: "Responder"
      form:
        fields:
          - slackId
          - email
          - slackUsername
          - department
          - jobTitle
          - teamLead
          - fullName
          - site
          - team
      list:
        fields:
          - slackId
          - email
          - slackUsername
          - department
          - jobTitle
          - teamLead
          - fullName
          - site
          - team
        actions: ['show', "edit", "delete", { name: 'asd', template: 'question/custom.html.twig' }]
        batch_actions: ["delete"]
        filters: ["teamLead"]
      show:
        fields:
          - slackId
          - email
          - slackUsername
          - department
          - jobTitle
          - teamLead
          - fullName
          - site
          - team

    Question:
      class: App\Entity\Question
      label: "Question"
      form:
        fields:
          - {type: "group", icon: "pencil", label: "Question info", css_class: 'col-lg-7'}
          - questionNumber
          - question
          - poll
          - options
          - {type: "group", icon: "pencil", label: "Options info", css_class: 'col-lg-5'}

      list:
        fields:
          - id
          - question
          - poll
          - answers
        actions: ['show', "edit", "delete", { name: 'asd', template: 'question/custom.html.twig' }]
        batch_actions: ["delete"]
        filters: ["poll"]
      show:
        fields:
          - id
          - question
          - questionNumber
          - poll
          - options

    Survey:
      class: App\Entity\Survey
    Poll:
      class: App\Entity\Poll
      list:
        actions:
          - { name: 'send_team', type: 'route' }
          - { name: 'send_workspace', type: 'route' }
    User:
      class: App\Entity\User
    Answer:
      class: App\Entity\Answer
    Option:
      class: App\Entity\Option
