easy_admin:
  list:
    # show the 'restock' action for all entities except those which remove it
    #actions:
      #- { name: 'Add_Poll' }
  design:
    menu:
      - {label: "Entities"}
      - label: "Questions"
        children:
          - {entity: Question, label: "List", icon: "th-list" }
          - {entity: Question, label: "Add", icon: "plus", params: {action: "new"}}
         # - {entity: Question, label: "Add to poll", icon: "plus", params: {action: "comming soon"}}
      - label: "Responder"
        children:
          - {entity: Responder, label: "List", icon: "th-list" }
          - {entity: Responder, label: "Add", icon: "plus", params: {action: "new"}}
      - label: "Survey"
        children:
          - {entity: Survey, label: "List", icon: "th-list" }
          - {entity: Survey, label: "Add", icon: "plus", params: {action: "new"}}
      - label: "Poll"
        children:
          - {entity: Poll, label: "List", icon: "th-list" }
          - { label: 'Add poll',icon: "plus", route: 'polls', params: {adminId: 1} }
          - {entity: Poll, label: "Add", icon: "plus", params: {action: "new"}}

          #- {entity: Poll, label: "Results", icon: "plus", params: {action: "show"}}
      - label: "Option"
        children:
            - {entity: Option, label: "List", icon: "th-list" }
            - {entity: Option, label: "Add", icon: "plus", params: {action: "new"}}
      - label: "Answer"
        children:
            - {entity: Answer, label: "List", icon: "th-list" }
            - {entity: Answer, label: "Add", icon: "plus", params: {action: "new"}}
      - {label: "Settings"}
      - {entity: User, icon: "user", permission: 'ROLE_SUPER_ADMIN'}
  site_name: "Nfq Pulse"
  user:
    name_property_path: "email"
    display_name: true
  entities:


    # List the entity class name you want to manage
    Question:
      class: App\Entity\Question
      label: "Question"
      form:
        fields:
          #- {type: "group", icon: "pencil", label: "Question info", css_class: 'col-lg-7'}
          - question_number
          - question
          - poll
          - options
         # - {type: "group", icon: "pencil", label: "Options info", css_class: 'col-lg-5'}

      list:
        fields:
          - id
          - question
          - poll
          - answers
        actions: ['show', "edit", "delete"]
        batch_actions: ["delete"]
        filters: ["poll"]
      show:
        fields:
          - id
          - question
          - question_number
          - poll
          - options


    Responder:
      class: App\Entity\Responder
      label: "Responder"
      form:
        fields:
          - slackId
          - name
          - email
          - teamLead
      list:
        fields:
          - slackId
          - name
          - email
          - teamLead
        actions: ['show', "edit", "delete", { name: 'asd', template: 'question/custom.html.twig' }]
        batch_actions: ["delete"]
        filters: ["teamLead"]
      show:
        fields:
          - slack_id
          - name
          - email
          - teamLead



    Survey:
      class: App\Entity\Survey
    Poll:
      class: App\Entity\Poll
    User:
      class: App\Entity\User
    Answer:
      class: App\Entity\Answer
    Option:
      class: App\Entity\Option